# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import products.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190802_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='filepath',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
