# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190802_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.CharField(max_length=120),
        ),
    ]
